# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        AppBundle\Entity\Login: plaintext

    providers:
        db_provider:
            entity:
                class: AppBundle:Login
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: db_provider
            anonymous: ~
            form_login: 
                login_path: homepage
                check_path: homepage
            logout:
                path:   /logout
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/livreur, roles: ROLE_USER }
