# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig_extension:
        class: AppBundle\Twig\StatExtension
        public: false
        arguments: ['@doctrine', '@security.token_storage']
        tags:
            - { name: twig.extension }
